# Generated by Django 4.1.7 on 2023-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
    ]
