# Generated by Django 4.1.7 on 2023-03-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='seller_address',
            field=models.BooleanField(default=False),
        ),
    ]
